language: java
jdk:
  - openjdk13
script:
  - cd webtools-parent
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

deploy:
  provider: script
  script: "cp ../.travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true